services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
        - db_user=moo_user
        - db_pass=moo_pass
        - db_name=moo_db
        - db_host=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - moo_network
      
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: moo_db
      MYSQL_USER: moo_user
      MYSQL_PASSWORD: moo_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5    
    networks:
      - moo_network
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - moo_network
volumes:
  db_data:
  caddy_data:
  caddy_config:
networks:
  moo_network:
    driver: bridge  
